export const HOTEL_LIST_REQUEST = 'HOTEL_LIST_REQUEST';
export const HOTEL_LIST_SUCCESS = 'HOTEL_LIST_SUCCESS';
export const HOTEL_LIST_FAIL = 'HOTEL_LIST_FAIL';
export const HOTEL_LIST_RESET = 'HOTEL_LIST_RESET';


