export const RESTAURANT_LIST_REQUEST = 'RESTAURANT_LIST_REQUEST';
export const RESTAURANT_LIST_SUCCESS = 'RESTAURANT_LIST_SUCCESS';
export const RESTAURANT_LIST_FAIL = 'RESTAURANT_LIST_FAIL';
export const RESTAURANT_LIST_RESET = 'RESTAURANT_LIST_RESET';
///////////////////////////////////////////////////////
export const RESTAURANT_CREATE_REQUEST = 'RESTAURANT_CREATE_REQUEST';
export const RESTAURANT_CREATE_SUCCESS = 'RESTAURANT_CREATE_SUCCESS';
export const RESTAURANT_CREATE_FAIL = 'RESTAURANT_CREATE_FAIL';
export const RESTAURANT_CREATE_RESET = 'RESTAURANT_CREATE_RESET';
export const RESTAURANT_REVIEW_UPDATE = 'RESTRAUNT_REVIEW_UPDATE';



